### ISSUE TITLE
Reading wrong slots in tournament mode

### ISSUE THREAD

**Issue by R0B11** [KotRikD/tosu#114]
Tosu does not seem to read the slots in the correct order/correctly. Here is an example:

![image](https://github.com/KotRikD/tosu/assets/114362409/dcdd241b-72aa-4b5f-a1fa-eaf5ceebb621)

![image](https://github.com/KotRikD/tosu/assets/114362409/a2b02cc0-f7ee-49e5-be52-9e22335002be)

**Comment by KotRikD** [comment]
version of tosu?
