### ISSUE TITLE
"installed" tab not working

### ISSUE THREAD

**Issue by lokillo-0** [KotRikD/tosu#119]
When i open the dashboard in the "installed" tab i get this error but in the others i have no errors
![image](https://github.com/KotRikD/tosu/assets/19214569/cf9c5fcf-7507-425a-9359-bf30ff7f6e95)

**Comment by cyperdark** [comment]
@lokillo-0 does it happens on new version?

**Comment by cyperdark** [comment]
closing because it's probably already fixed
