### ISSUE TITLE
laggy keyoverlay

### ISSUE THREAD

**Issue by Miyuki-10** [KotRikD/tosu#130]
keyoverlay very laggy ingame and also inside obs, but extremely smooth when watching on the http://127.0.0.1:24050 browser in the dashboard

[key overlay by cyperdark](https://github.com/cyperdark/osu-counters/tree/master/counters/KeyOverlay%20by%20cyperdark)

![image](https://github.com/KotRikD/tosu/assets/93956624/e7e4b1cf-dc5e-4823-850b-852205cb138b)

**Comment by KotRikD** [comment]
PC Specs?

**Comment by cyperdark** [comment]
Record a video, how it's in dashboard, obs, ingame

**Comment by cyperdark** [comment]
@Miyuki-10 do recording again, but add in obs task manager window, and make sure it's readable

then in task manager expand osu, so we can gosu overlay stats too

**Comment by cyperdark** [comment]
i dont want to deal with it, ask someone on server to help you https://discord.gg/WX7BTs8kwh
