### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by Miyuki-10** [KotRikD/tosu#140]
The issue is right now tosu only works if you have the location of the folder in Desktop. It will not work in "Program Files" or other paths location.

Just like gosumemory and stream companion where it works on any location. That should just be a default thing. And going into properties and add the flags to allow it. It's not a optimal way to do that.

**Comment by cyperdark** [comment]
run as administator doesnt exists, right?


https://github.com/KotRikD/tosu/assets/21735205/ab31f942-ff70-4d81-8a8f-f8b7e80ea9d1
