### ISSUE TITLE
Can someone make this two overlays as one?

### ISSUE THREAD

**Issue by Daniil15DDD** [KotRikD/tosu#148]
![image](https://github.com/KotRikD/tosu/assets/136138558/b659eb0d-1038-4f3e-8e3e-9929018c7af7)

**Comment by GabuTheDev** [comment]
Please refrain from opening an issue if it's not related to either a bug or a feature request.

I do understand you need help with something related to tosu, but GitHub issues is not the place to ask for general help with coding, use [the discord server](https://discord.gg/WX7BTs8kwh) instead.
