### ISSUE TITLE
add beatmap objects amount

### ISSUE THREAD

**Issue by cyperdark** [KotRikD/tosu#15]
![image](https://github.com/KotRikD/tosu/assets/21735205/0ac8e4e6-05d6-48ac-b3fd-5448b2683af9)

**Comment by KotRikD** [comment]
Ahh, not sure about that, need RFC for all gamemodes based on old osu code

**Comment by cyperdark** [comment]
isnt you already parse beatmap?

**Comment by KotRikD** [comment]
> isnt you already parse beatmap?

oh fr true
