### ISSUE TITLE
Feature Request: Adding current Mapposition (time) to precise Data

### ISSUE THREAD

**Issue by thedarklort** [KotRikD/tosu#154]
Title. Adding the current timestamp in the map to the precise Data would be amazing

**Comment by cyperdark** [comment]
are you talking about `beatmap.time.live`? @thedarklort

**Comment by thedarklort** [comment]
Hi, yes exactly

**Comment by cyperdark** [comment]
@thedarklort try this build https://github.com/KotRikD/tosu/actions/runs/9684743186/

**Comment by thedarklort** [comment]
works fine, now speeding up the game dosent interfere with the keypresstimes
