### ISSUE TITLE
Program sometimes abruptly quits when scanning memory

### ISSUE THREAD

**Issue by KittyLikeme** [KotRikD/tosu#159]
Sometimes it starts up successfully but sometimes it cuts off abruptly and requires a handful of startups for it to work. This happens with and without administrator

https://github.com/KotRikD/tosu/assets/117192303/2468a75e-f55d-49ee-b9e3-87623b5e54b3

**Comment by cyperdark** [comment]
@KittyLikeme enable debug log in tosu.env, and record video again

**Comment by cyperdark** [comment]
@KotRikD

**Comment by cyperdark** [comment]
@KittyLikeme hello, can you test this build? and also enable debug log, so we can see at what exact moment it crashed
https://github.com/KotRikD/tosu/actions/runs/10296241047
