### ISSUE TITLE
Cound't read int (HitErrors) and `null pointer` issue in gameplay

### ISSUE THREAD

**Issue by durashcka** [KotRikD/tosu#169]
The first run of tosu work fine until  i see that pp counter doesn't show pp for map in play and when i switch to the tosu i'll see this error message 
![изображение](https://github.com/user-attachments/assets/77cc18db-9e85-4180-8eb3-7594b3502649)
After restart tosu works for like 1 map and i'll see another error message
![изображение](https://github.com/user-attachments/assets/8b118f83-06bc-4224-9b14-9f4792210845)
And after another restart tosu after 1 map i'll see another error message 
![изображение](https://github.com/user-attachments/assets/89654ffa-40b0-4eb5-90e7-a494e2e54153)

**Comment by cyperdark** [comment]
![image](https://github.com/user-attachments/assets/196325da-a0a3-474f-a536-39a73e317a6e)
