### ISSUE TITLE
tosu linux version trying to access absolute path as relative

### ISSUE THREAD

**Issue by KittyLikeme** [KotRikD/tosu#177]
My osu config file has an absolute path set for my songs folder but tosu is trying to access it relative to the startup directory

![image](https://github.com/user-attachments/assets/e8f30fef-5812-4dcd-8205-9284de33d9d8)

![image](https://github.com/user-attachments/assets/ea13c932-da55-4614-b581-0f8f9f89e08e)

**Comment by cyperdark** [comment]
join discord, will ask questions here https://discord.gg/tvTJqTV3
