### ISSUE TITLE
Feature Request: More hits / judgements

### ISSUE THREAD

**Issue by UniverseMultiverse** [KotRikD/tosu#183]
I found these on osu lazer. I don't know if it's possible to be added in Tosu.

![image](https://github.com/user-attachments/assets/7c091aa1-74f9-4256-be14-3ad9fdbe1ee6)

In osu standard there are slider tick, slider end, spinner bonus, spinner spin.

![image](https://github.com/user-attachments/assets/58a57933-02cd-41d8-b79d-8071cf77cbde)

In osu taiko there are bonus and drum tick.

![image](https://github.com/user-attachments/assets/d9f1da9b-428d-42ee-a590-c45c3debaabc)

In osu catch there are Large Droplet, Small Droplet and banana.

Here are the videos on how these work:

https://github.com/user-attachments/assets/7fdc73d5-595c-4b9b-8f3a-5d6ea97db39e

https://github.com/user-attachments/assets/1d306a62-e852-4e5d-88c0-d6df7c82b673

https://github.com/user-attachments/assets/9cb9a123-e631-4641-9033-bd77f48bde88

**Comment by cyperdark** [comment]
i dont think that information exists on stable

**Comment by cyperdark** [comment]
@KotRikD

**Comment by KotRikD** [comment]
I can't find those attributes on stable map info, calculating it don't think is possible at current stage
