### ISSUE TITLE
Expose skin assets through tosu API

### ISSUE THREAD

**Issue by happpy24** [KotRikD/tosu#194]
To incorporate overlays more with the skin the user is using, I think grabbing the skin elements from the current skin and using them in an overlay could be really cool

Example: Currently grabbing the beatmap image goes like this: `http://127.0.0.1:24050/files/beatmap/${background_path}` where `background_path` == `directPath.beatmapBackground.replace(folders.songs, '');`

Allowing us to grab for example mod icons from the current skin being used, could make an overlay where the mod icons never disappear. Or grabbing the star.png object and making our own kiai celebration.

Could be cool but is by no means priority depending on how difficult this would be to implement (im still bad at typescript)

**Comment by cyperdark** [comment]
/files/skin/{path}
