### ISSUE TITLE
randomly pause/stuck

### ISSUE THREAD

**Issue by cyperdark** [KotRikD/tosu#5]
Smth program will stuck in one state and will do nothing

also why it's over 1gb of memory
![image](https://github.com/KotRikD/osumemory-ts/assets/21735205/58682544-5f30-4978-9600-8290e6a3e1c7)

**Comment by cyperdark** [comment]
i notice that this happen after a couple of map retries (while watching replays)

**Comment by cyperdark** [comment]
potential in https://github.com/KotRikD/osumemory-ts/commit/10529a274e436759c40e88ea88473e85d624238c

**Comment by cyperdark** [comment]
still randomly freezes

**Comment by KotRikD** [comment]
probably fixed in [edd0e6a](https://github.com/KotRikD/tosu/commit/edd0e6a429fc17094e4e599e3912b0f59f84be63)

**Comment by cyperdark** [comment]
pauses on startup are gone 👍

**Comment by cyperdark** [comment]
didnt notice any since the fix
