### ISSUE TITLE
User current stats

### ISSUE THREAD

**Issue by cyperdark** [KotRikD/tosu#7]
Can we have those stats: Rank, pp, acc, lvl from this box:
![image](https://github.com/KotRikD/osumemory-ts/assets/21735205/3f4eed65-6204-44ea-8476-cbb7441b9c66)

**Comment by KotRikD** [comment]
This data can be grabbed, I will look what I can done

**Comment by KotRikD** [comment]
done in [22ec473](https://github.com/KotRikD/tosu/commit/22ec47356d16805e139901950924a0b8fcd2bb92)
