### ISSUE TITLE
Installed counter preview disappears in the webUI after server restart.

### ISSUE THREAD

**Issue by GabuTheDev** [KotRikD/tosu#79]
I encountered this issue specifically on `basic-unstable-rate` counter, the others seems to be working just fine after server restart, although I haven't tested all.

https://github.com/KotRikD/tosu/assets/107962621/a425da7c-fdc1-451c-bd80-d1abbb0c9922

**Comment by cyperdark** [comment]
https://github.com/cyperdark/osu-counters/blob/master/counters/basic-unstable-rate%20by%20cyperdark/index.js#L39
