### ISSUE TITLE
Change preview media in the installed section to a fixed width to fit the viewport.

### ISSUE THREAD

**Issue by GabuTheDev** [KotRikD/tosu#81]
Preview media is shown fully in the `Available` section but after installing and switching to `Installing`, the preview does not fit the card anymore, it uses the original picture size.

Another mention: preview media in the `Installed` section uses a different path compared to the ones presented in the `Available` section, which can be confusing for some people.

https://github.com/KotRikD/tosu/assets/107962621/25b0e044-f2d7-421b-88b1-d5980cc687f5

**Comment by cyperdark** [comment]
uhm? they using `installed` uses iframes to display live pp counters

**Comment by GabuTheDev** [comment]
> uhm? `installed` uses iframe to display live status of the pp counter

You're simulating it or it's just a gif?

Also, this doesn't answer my request. The image in the `Installed` section is not fully shown. I can't see the right of the preview image because it's out of view. I just wanted a `max-width` for images in the cards.

**Comment by cyperdark** [comment]
> You're simulating it or it's just a gif?

`available` have images
`installed` have iframes, and i believe you cant resize iframe to container size, without losing content of page

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
