### ISSUE TITLE
Add support to KeyOverlay for mania and taiko

### ISSUE THREAD

**Issue by cyperdark** [KotRikD/tosu#92]
idk if it even has per key stats, but keypresses should be somewhere

for future

**Comment by KotRikD** [comment]
![image](https://github.com/KotRikD/tosu/assets/23283658/64b58e30-67dd-4cbf-ae45-3d011c0f2daf)
fck

**Comment by 0CYW** [comment]
Unless I misunderstood something, you could just get the keycode for the buttons and add getKeyboardState in tsprocess and handle key presses stats yourself

**Comment by cyperdark** [comment]
@0CYW replays support?

**Comment by breadles5** [comment]
> @0CYW replays support?

crap i didnt think of that. in which case anyway, if osu has a way to scan keyboard input and register them to a key input i.e. d = key1, f = key2, etc, they should be somewhere in memory.

**Comment by 0CYW** [comment]
> @0CYW replays support?

oh, I forgot about that, then you should be able to use InputManager.lastButtonState as InputManager sets it to the replay's buttons state too if player was spectating/watching a replay

**Comment by KotRikD** [comment]
Okay, Cherry found place, that we can potentially use, but now I have some worry about couting in those mods, like osu! dont have counters for that inputs)

**Comment by Anti-Apple4life** [comment]
Just curious, are there any plans for this in the future?

**Comment by cyperdark** [comment]
@KotRikD to afraid off adding it cuz he worked about counting keys issues, since doesn't have it for mania and taiko

**Comment by 0CYW** [comment]
> [@KotRikD](https://github.com/KotRikD) to afraid off adding it cuz he worked about counting keys issues, since doesn't have it for mania and taiko

How about reading the replay frames to count the keys? should be pretty simple, I can PR the change

**Comment by Anti-Apple4life** [comment]
> @KotRikD to afraid off adding it cuz he worked about counting keys issues, since doesn't have it for mania and taiko

Also I think Lazer does count the mania and taiko keys if I am not mistaken

**Comment by KotRikD** [comment]
> > [@KotRikD](https://github.com/KotRikD) to afraid off adding it cuz he worked about counting keys issues, since doesn't have it for mania and taiko
> 
> How about reading the replay frames to count the keys? should be pretty simple, I can PR the change

Repo is open for any PR :) https://github.com/tosuapp/tosu/blob/master/CONTRIBUTING.md

**Comment by KotRikD** [comment]
> > [@KotRikD](https://github.com/KotRikD) to afraid off adding it cuz he worked about counting keys issues, since doesn't have it for mania and taiko
> 
> Also I think Lazer does count the mania and taiko keys if I am not mistaken

The original speech was about the stable version, we need to look and think, we still don't plan to add it.
