### ISSUE TITLE
Wrong Information in Tournament Client mode

### ISSUE THREAD

**Issue by R0B11** [KotRikD/tosu#93]
Current setup:
- 2v2 tournament client (cutting edge)
 
Chat is very inconsistent with the memory issues. Sometimes, teams are on the opposite side of what they are supposed to be. Other times (after restarting tosu), everyone is assigned the left team.
In the socket message
- gameplay was set to the very last user (slot 4/4), where all of the details were shown for that player's screen).
- results screen is the same as above
- this does not resolve if i move to a new lobby (with nobody in it)

in:
tourney.ipcClients
Tested with 2 players in the lobby - player_a was in slot 2, player_b was in slot 4.
- ipcClients[0] had everything for player_b (in slot 4)
- ipcClients[1].spectating showed the details of player_a (there was no scores)
- ipcClients[2].spectating showed the details of player_a (there was no scores)
- ipcClients[3] had everything for player_a (in slot 2)

**Comment by KotRikD** [comment]
Will check today

**Comment by KotRikD** [comment]
@R0B11 can you test with https://github.com/KotRikD/tosu/actions/runs/8188473321/artifacts/1305813083 this build?

**Comment by KotRikD** [comment]
UPD: I uploaded v2.3.2 release, it should contain this change, so if you open your tosu it should automatically update to this version and get changes, so you can not download build

**Comment by KotRikD** [comment]
#99
#101
